language: c
before_install:
- curl -Ls http://s3.voneicken.com/xtensa-lx106-elf-20160330.tgx | tar Jxf -
- curl -Ls http://s3.voneicken.com/esp_iot_sdk_v2.0.0.p1.tgx | tar -C .. -Jxf -
script:
- export XTENSA_TOOLS_ROOT=$PWD/xtensa-lx106-elf/bin/
- export BRANCH=$TRAVIS_BRANCH
- export TRAVIS_TAG=$(echo $TRAVIS_COMMIT | cut -c 1-7)
- echo "Travis Branch is $TRAVIS_BRANCH"
- echo "Travis Tag is    $TRAVIS_TAG"
- echo "Travis COMMIT is $TRAVIS_COMMIT"
- echo "Travis COMMIT is $TRAVIS_COMMIT_RANGE"
- echo "Dont forget to set VARIABLES for S3 to function. SEE gof3r README. AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY"
- make release
notifications:
  email: false
  
deploy:
  overwrite: true
  skip_cleanup: true
  provider: releases
  api_key:
    secure: unYyTCLpk1ixcNOyoUwroBqqx0yBhii56IXm57kjo5kl3umf1GRb3FUIE6la+B0njsNwAUNR/uLn6wF4FqYTUJzNQZskJDJfZjb53vwuoHaoa5j4K/bWB9zRlQ1XZBTkV48cxz8Ef2KyNduK2IciOHwsw3LQS0em3dpK7oG/20VzELt23Gx8uhBYa+OUzlr3Y+PYPynkwM30YwVQXpCy/GMgEbrcKheGbLTAIp7tms0KDAvbb98U0BI3tWBckE5GzAYYAmrXgyDXtEsU/poCMqUj/lpPl1s/5uxGVevTO7XuL4AYtF//AixsM20bPKtIZDHZS9b7JHtVhU655bY2aAfpMgf7xzkKbJkRzeAzT9HucFDjLY48yW4vztdJxBgkAL9d064gTHhThtn4hylZAYpHnqUiM0j4DKil5A0VG2F8EVEqZ7Q2tNzy6aqq37wzTuYXsYpz3mglpazaXXp/LoSurDHy1gz6aB/mdaeBoL3MX1q09LBE8lFGYBILQ8KUkrLyJathxAVvDBnl7nXFv2NWoZ2i7CfXdpCwmOVUN2WhudNfgbbaMung+voTFB+yLq9PBQP5gdP0MKU3zDTB/msmZo1pp/SbnNETCrKAdRtxNI+bxTQ98njAIkxI+7ZiVV8SMNEPyNcWq/6ViYDcIHJMR4Gq0DZunre1voEs1F4=
  file_glob: true
  file: esp-link-*.t*gz
  on:
    tags: true
    branch: testing
    repo: fuzzball03/esp-link

after_success:
- cd $TRAVIS_BUILD_DIR
- rm -rf ./build
- tar --exclude=*.t*gz -czf ../esp-link-$TRAVIS_BRANCH-$TRAVIS_TAG-source.tar.gz $TRAVIS_BUILD_DIR
- mkdir -p release
- mv esp-link-*.t*gz $TRAVIS_BUILD_DIR/release
- mv ../esp-link-*.t*gz $TRAVIS_BUILD_DIR/release
  
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  acl: public_read
  upload-dir: travis-builds
  local-dir: release
  on:
    branch: testing
    repo: fuzzball03/esp-link
